---
title: Proceedings of Machine Learning Research
booktitle: Proceedings of the 6th Northern Lights Deep Learning Conference (NLDL)
shortname: NLDL
year: '2025'
publisher: PMLR
series: Proceedings of Machine Learning Research
volume: '265'
start: &1 2025-01-07
end: 2025-01-09
published: 2025-01-12
conference_number: '6'
layout: proceedings
issn: 2640-3498
id: nldl2025
month: 0
tex_title: Proceedings of the 6th Northern Lights Deep Learning Conference (NLDL)
cycles: false
bibtex_editor: Lutchyn, Tetiana and Ram\'irez Rivera, Ad\'in and Ricaud, Benjamin
editor:
- given: Tetiana
  family: Lutchyn
- given: Adín
  family: Ramírez Rivera
- given: Benjamin
  family: Ricaud
description: |
  Proceedings of the 6th Northern Lights Deep Learning Conference (NLDL)
    Held in UiT The Arctic University, Troms\o, Norway on 07-09 January 2025

  Published as Volume 265 by the Proceedings of Machine Learning Research on 12 January 2025.

  Volume Edited by:
    Tetiana Lutchyn
    Adín Ramírez Rivera
    Benjamin Ricaud

  Series Editors:
    Neil D. Lawrence
date_str: 07--09 Jan
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v265"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v265
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v265
email: ''
conference:
  name: Northern Lights Deep Learning Conference
  url: https://www.nldl.org
  location: UiT The Arctic University, Tromsø, Norway
  dates:
  - *1
  - 2025-01-08
  - 2025-01-09
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v265/nldl2025.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v265/nldl2025.bib
